language: python

python:
    - '2.7'

cache: pip

install:
    - pip install openpyxl

script:
    - cd ./test
    - python ./datatype.unittest.py
    - python ./io.unittest.py
    - python ./selection.unittest.py
    - cd ../
    - python ./AltiumNetlistGen.py > ./WARNINGS.log

deploy:
    provider: releases
    api_key:
        secure: "Y4AXiFA4b5bzjU424TPMF3yIhsZyrwwDBxxT3WTS1z5rFL+YUhNt1hGTXojVEflL4cNccRklWZ3c31SY/gqfxUzxDkRKBYxsOefm3+gVDdtDRto8uhYMSmMV4pyjoIWhfooOrLn08yxtASJfyFmQNVb6VVbXAuhvNdYRhpgLkLmR5xvzcmXgMXuLXHQgZxiXsjRMcC+iyBNoGxjmChlD/XUvi/yGYNzk/Si4PLHUiFMvnUf67jOqE2WtylZuLVH56HAIKaROY2enOYfsQBAqJfhxJ5cVEHqFPOgZwoPjM0GDpjRQIdEuGKm9cbRC9Tz3SWXg7f3WH0UeaTJmM1/s9FEcigCLKQxm+aDYFRIGKdL08IQE6s3vl8Y5sGqM7r8w/KPxUj3IkMVoVjY3C6IrJfiGTcaEXytuZtLLNjBXWkvVEP3ibbyUA1o3nUvwbpd+e0WnMri24e+38UIjgVvH56TRVlUBjVdLumZ9V6oUD2lMT7mVnadBJylU6sQt0Vi/FGXL8Z+1iUUF4/2FZOc31h9odEK6JpJ1EloY3o+qQNVBbZ/l95EkZOjCWibzSjFgAem8SLgNHq52J3Q1Qi1EqTQ41n2+9lOvmJ456cou/8eiDP5ymkPaYsCPeyx3yHSfOB/3ksc9hpr6KmzIxXTpFxG07uq4mT7/Yenj9S7K7IA="
    file:
        - "./WARNINGS.log"
        - "./gen/AltiumNetlist_PT.csv"
    skip_cleanup: true
    on:
        tags: true
