language: python

python:
    - '2.7'

cache: pip

install:
    - pip install openpyxl

script:
    - cd ./test
    - python ./datatype.unittest.py
    - python ./io.unittest.py
    - python ./selection.unittest.py
    - cd ../
    - python ./AltiumNetlistGen.py > ./WARNINGS.log

deploy:
    provider: releases
    api_key:
        secure: aeEf4eoJiaapm7d52iHv/vmeTftay+aHBhzqgT2W3BtUlX9ZvSMUcTvN9kis4YlxGi0b6RVtwviOtq7OirFdAgVkcxzodU2UOcTWXnig341woZoppM6/QhSG5E0jWdl8Uc/ittr3O+r7IFqp/xo4pA8TFYuD/JOwhhrIzbdZaih4ARHqCWg/1nthX4znhVBUM4TEJSnCuNfGX2c+MZTuezXi0dL0bRpe/6xpnfHATHMJ4ANjUENmFuNkFkdVRc012xLIY9FlRE0PMFjQfqbCkr7b4c/JWtpjUUcg86U7ojZ4nJESlef1HZAF/6h9UIJs5lg7kRsxGBlGiDbfnfTAJJ5aZnTHikwhENIzLhBcQQGodlSe+I63TmSVcFPQiPZUPa8ZH+kWPtpJ/KCpv/t7nxo4KPht6YIcp0et4WB3yEYZdBse/Od+ayMCO2xmIWIqjzBv6Jfz1SC7wcLpgGV8ri4vXCiImGXhYiBBUZBWNZUsKaLOw7m1Vsw4lYtqjSuzvqR09UXQSjtGkxgarZIl3P3APN2s5ygmvE8xrQ1J5BYLrtSrFKvOCKuPy5hK3A/YhDmTQQ9jp9kGZyJgSu95z+V2trZ0UWSjBhRBErCTNCMUyL4oMt189gzIGVI2zHVWZao8Fl3x1v+RKhX9lzwHC3bFGepukb8UI7eb1ql+Cw4=
    file:
        - "./WARNINGS.log"
        - "./gen/AltiumNetlist_PT.csv"
    skip_cleanup: true
    on:
        tags: true
