language: python

python:
    - '2.7'

cache: pip

install:
    - pip install openpyxl

script:
    - cd ./test
    - python ./datatype.unittest.py
    - python ./io.unittest.py
    - python ./selection.unittest.py
    - cd ../
    - python ./AltiumNetlistGen.py > ./WARNINGS.log

deploy:
    provider: releases
    api_key:
        secure: "mDC9ICK9hTTEH6QUoaWJ57r5Qn6fix1fBB0iiQHb9PIqTIPrP7pmdLpYOW1B7Dj3iYv1OC3GGQjEZCw7p0D/81Eu2cuYv06rUYEbsBwV5n9VAtKpFo197p4HUXQ0FdwyMi55SVKCrYjI2a314Xe4kut7YzKWXdXrgpQfKw2wQYgAuaIYpn36/WnLP8YIzRNThH5Iu0urpfrj7vni80uooFRPbzu4LGNPj0EAPjLfxYk+hetL8E5N4h5FQ++ofQ3LPB3yJq9/mlRxVBOeB6Tr1mvSSSsuiRFpKsFpphcfxLZ3205xFqbnnmCB33krrv/IFMNA38SxN4ejJQpLnp4CqVoOJVJRCzNziQwJrtnvgjCiac0DP6qwspwfb613eRQLnoanhmgK5hNXA5VZNsP2hNIYTVqJMTgNkWTpBDyreBXJxNcAz2nPX1oAn7N8EAULNz4Ov1gItFTBppyd8+Y2dwv1e1kQlTNBSSoySOD5u/ZuQnkp54stbhK6O3Ga+z+LSe1FBcjB/6pDJTgAglU5KxVL38Q2Fm93nks7JudbQsjjooYkQsLHZB7yQgnAnx5UYsfxdGwQxzl/WEGRDYUGyZVGuwHYM6J2+V/s42BBWVwl2X1LT1FMukmDnMi5F4zD0ZKFrjEpB/pBj9XdNVHdk5GReYi9FPH8XZlQ/Jk8Fuc="
    file:
        - "./WARNINGS.log"
        - "./gen/AltiumNetlist_PT.csv"
    skip_cleanup: true
    on:
        tags: true
