language: python
python: 3.8

cache: pip

install:
    - pip install -r ./pyUTM/requirements.txt

script:
    - ./FiberAsicMap.py
    - travis_wait 30 ./NetlistCheck.py ./input/backplane_netlists/backplane_true_type_ZSYang_10Oct2019.net Warnings_TrueType.log
    - travis_wait 30 ./NetlistCheck.py ./input/backplane_netlists/backplane_mirror_type_PhoebeH_26March2019.net Warnings_MirrorType.log

deploy:
    provider: releases
    api_key:
        secure: "SsjEeAy91OjJrqHt+VqT0yc4ZktDxgcqE2G29E9rgp55U4VFQu9m8XG8Xf2lzjVGBVII/8F5s1X+6gZswYzP2lqqUnwuFKBs4Cxwml22bE+/sWHR2bx7334p04JJpKHGIou9Mwf6xeDvB+qNV5pOwEGzLB9jp39Y6KIEGV2AOtkUiL3T8HG6JSmvAcm7+M4XvxIwhl+RA+oounKCNLJ2NyGeAjj9irZ/RVS1BTBm+A+fIYmWd1KUBbtDP5ok8i9hwo5EQWiODsVdIwIoJekoOWLmZ4QkkXDpK8IqDK3iCurEWcUhE8KfcPbuthAar7tHrdBNmJUbNPfprijSWKcqx9IH6xcXaNKMmYRcns66rmnKSbizkxFdDz39pi4xNNG9xPuN6YiU5XMOOgo4r+wvajb8KlrEtzdLTHrGhJLSpAKn+iuZ5tMfYL/gfdE1ULDOcOEM9LaDOzG1YANmr14VDOcnvncemiYIzEOd8peupmaoWBvR8o/IpcbuO7vd9qyO4fuK2zeGe4dLcL5NQbS7GJ0Nb+Dv6w4Q1cwTO8j03a0QBUZD79Ub6epesgGC/n0ymR22N4xO8j0l9RHoTKBTafD1FJy68SD/QLtk35q0eWcgZcjICuLPpE+gYV5CvsVfH1QJFED1VJe2WN/UInUrF534KeYl/lYSPp3trPoG6VM="
    file:
        - "./output/AltiumNetlist_PT_Full_TrueType.csv"
        - "./output/AltiumNetlist_DCB_Full_TrueType.csv"
        - "./output/AuxList_PT_Full_TrueType.csv"
        - "./output/AltiumNetlist_PT_Full_MirrorType.csv"
        - "./output/AltiumNetlist_DCB_Full_MirrorType.csv"
        - "./output/AuxList_PT_Full_MirrorType.csv"
        - "./output/AsicToFiberMapping.csv"
        - "./output/Mapping_PT_TrueType.xlsx"
        - "./output/Mapping_DCB_TrueType.xlsx"
        - "./output/Mapping_PT_MirrorType.xlsx"
        - "./output/Mapping_DCB_MirrorType.xlsx"
        - "./Warnings_TrueType.log"
        - "./Warnings_MirrorType.log"
    skip_cleanup: true
    on:
        tags: true
