language: python

python:
    - '2.7'

cache: pip

install:
    - pip install openpyxl

script:
    - cd ./test
    - python ./datatype.unittest.py
    - python ./io.unittest.py
    - python ./selection.unittest.py
    - cd ../
    - python ./AltiumNetlistGen.py > ./WARNINGS.log

deploy:
    provider: releases
    api_key:
        secure: "oTP3Tgtpvpng4oknRZtUcQyQ3LuvlSAEQ96U4Gs1UllNhg24oT63I7pjsBq+TxhYV9dZxO/WgsCD1akTrKkp27Gmxzvy/jbnViIeRV5VEYHXoff8I3SibYJKMEcgyILTF52kJXvUT9vyGT84P6j5NKgb8xqxtN9DuHJ+NMReSKaFwsWlWw5g5eeQj12EQlkzmu8yyPUwstMqhoc2UArn06zvYR3sIbPfKJjt6zCSS5omhWoooRJFNxN+Ccna0/pUlAtJKz2NQmXXlxvBWqZ/Kbl6JrCHA2DqwFqUTu6us0JBeA0+b0wnRuC2RS44w8RefDJPlSuFmOLx7O02P1U7wQEjrpfadhRRScvKuNqTd0SzPQj8ACYwUcrGtIQ0Dn9nbEb85gCkIBj5PPuEzQqR+y3IUQLXj3ZWLK5kEB5pKTZU9HM4g+LboGr2wWswMtHi8Mk2L7JS74FDQSfzrQkgd95unyiGRRNCKIXimm+lBv4BVqkIPM/7gk77cO/QgLOWnNa+fkEhxPZASD4EJ9kY7oFBSbXzyuZfDuF1PpiY3pahuwgC8CJqDMTYFDWoSlJgTfF5kuYEFI6CreNY7JDqjsFRG0XdRKUac6ZCYueTejcrXo1bGss7ZW/hBOYO4sN9sFthZPLBm9ajIBuAuxOmF2SabHkd168tHgLj1oSVyCA="
    file:
        - "./WARNINGS.log"
        - "./gen/AltiumNetlist_PT.csv"
    skip_cleanup: true
    on:
        tags: true
