language: python

python:
    - '2.7'

cache: pip

install:
    - pip install openpyxl

script:
    - cd ./test
    - python ./datatype.unittest.py
    - python ./io.unittest.py
    - python ./selection.unittest.py
    - cd ../
    - python ./AltiumNetlistGen.py > ./WARNINGS.log

deploy:
    provider: releases
    api_key:
        secure: "Z9q42DkYwWHFrqatmkq2zCBjeI9OFXNRLI85aJTJTnH49sJrfLOJ9XCZz/qX55k7N2jZMVp/tk+8a5r4gXDP/TuusP+Lzp85DCjpRHPJciMHmRugmp21h5rzxSMjlIxHnKxnW9YVEZHpEB+9ehaPVqweRz6hFNXyPgqnNucfka612UoFhwvnzJP6fxCO2kV38QvF1g8HU9FcYmeb2FrgD4qLKPMaPwDx3HEwlz8FPJ3TpUSap02N2Qy0Re7v9lxoW4vhzo3dFr1NH3KlfChcqhCi4Fg0XQ5I2AvukbtNFsR/GDMgL5nYvC3CDu4UJA/ARnSwHAX9OfKFRVvlYOdxUPofxJSWSyVPUXI4V8VEKRI3D09Hq/eBoGpac5p1j9yn8FI6cXRNPnu+TMCRboYy8qrXFX9jNolH/fooDcW2+B4tGNH5S3ysn95Li3OPCybasDRjOwy51rQZFa+iUlbWkFj54cdAtqasQ21t3hkVlJmh/tqAM7uf/JssvusUWrKxOLtPTFRn2M2O6k6lVuc/DABM2ew50U2F9V0QD37Dfz6U4P11bYJv+6MR/MF5de+2JicgFXcUXR2PEHd+p6bAjuP95oa0V2U8PJOnIGOW/CQF6b+7js4heprv8Ulf28wePT+3VpC4MBMuU4W0Bqwe44He+UIG+efVAtN4XYs5bZk="
    file:
        - "./WARNINGS.log"
        - "./gen/AltiumNetlist_PT.csv"
    skip_cleanup: true
    on:
        tags: true
